adding tlp v2 and new object icons
traut/stixview pull request #26
Opened 2024-07-05 12:25 UTC by himynamesdave

2024-07-05 13:24 UTC, traut commented on README.md
> +* [Examples of various configuration settings](dist/demos/misc.html)
Relative links would point to the source files, not to the versions hosted at `traut.github.io/stixview`. The hosted versions are ready-to-use, which is valuable, I think

2024-07-05 13:35 UTC, traut requested changes

2024-07-05 13:35 UTC, traut commented on README.md
> +```
nice, thank you for the markdown cleanup!

2024-07-05 13:35 UTC, traut commented on icons/bank-card.svg
is it a new official object type or a custom one?

2024-07-05 13:35 UTC, traut commented on icons/x-eclecticiq-hypothesis.svg
> -</svg>
rip! 😄

2024-07-05 13:35 UTC, traut commented on src/icons.js
> +    '!svg-inline-loader?removeSVGTagAttrs=false!../icons/weakness.svg');
❤️

2024-07-05 13:35 UTC, traut commented on src/icons.js
> +    '!svg-inline-loader?removeSVGTagAttrs=false!../icons/user-agent.svg');
aha, clear now! all good

2024-07-05 13:35 UTC, traut commented on src/icons.js
>          color: color,
with the removal of line 222, this var `color` becomes undefined, I suspect

2024-07-05 13:35 UTC, traut commented on src/data.js
> +            'value': 'WHITE',
should we follow a STIX2 tlp-marking dict and have these as lowercase?

2024-07-10 12:49 UTC, himynamesdave commented on src/icons.js
> +    '!svg-inline-loader?removeSVGTagAttrs=false!../icons/weakness.svg');
ha, i removed it only b/c I'm 100% sure it's not used anymore. Plus, this is a deprecated custom object type

2024-07-10 12:49 UTC, himynamesdave commented on README.md
> +```
ha, was more a reminder for myself really

2024-07-10 12:50 UTC, himynamesdave commented on icons/bank-card.svg
it's a custom type I created. All of the new SCOs added in this commit

2024-07-10 12:51 UTC, himynamesdave commented on src/data.js
> +            'value': 'WHITE',
ah, good point

2024-07-10 12:57 UTC, himynamesdave commented
Sweet! I've pushed an update based on your feedback

2024-07-14 11:08 UTC, traut commented
merged in the scope of https://github.com/traut/stixview/pull/27

2024-07-14 11:08 UTC, closed without merging